/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as FaviconDotsvgRouteImport } from "./routes/favicon[.]svg"
import { Route as DsRouteImport } from "./routes/ds"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProtectedAccountRouteImport } from "./routes/_protected/account"
import { Route as ApiImagesOptimizeRouteImport } from "./routes/api/images.optimize"

const FaviconDotsvgRoute = FaviconDotsvgRouteImport.update({
  id: "/favicon.svg",
  path: "/favicon.svg",
  getParentRoute: () => rootRouteImport,
} as any)
const DsRoute = DsRouteImport.update({
  id: "/ds",
  path: "/ds",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: "/_protected/account",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesOptimizeRoute = ApiImagesOptimizeRouteImport.update({
  id: "/api/images/optimize",
  path: "/api/images/optimize",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/ds": typeof DsRoute
  "/favicon.svg": typeof FaviconDotsvgRoute
  "/account": typeof ProtectedAccountRoute
  "/api/images/optimize": typeof ApiImagesOptimizeRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/ds": typeof DsRoute
  "/favicon.svg": typeof FaviconDotsvgRoute
  "/account": typeof ProtectedAccountRoute
  "/api/images/optimize": typeof ApiImagesOptimizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/ds": typeof DsRoute
  "/favicon.svg": typeof FaviconDotsvgRoute
  "/_protected/account": typeof ProtectedAccountRoute
  "/api/images/optimize": typeof ApiImagesOptimizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/ds" | "/favicon.svg" | "/account" | "/api/images/optimize"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/ds" | "/favicon.svg" | "/account" | "/api/images/optimize"
  id:
    | "__root__"
    | "/"
    | "/ds"
    | "/favicon.svg"
    | "/_protected/account"
    | "/api/images/optimize"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DsRoute: typeof DsRoute
  FaviconDotsvgRoute: typeof FaviconDotsvgRoute
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ApiImagesOptimizeRoute: typeof ApiImagesOptimizeRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/favicon.svg": {
      id: "/favicon.svg"
      path: "/favicon.svg"
      fullPath: "/favicon.svg"
      preLoaderRoute: typeof FaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ds": {
      id: "/ds"
      path: "/ds"
      fullPath: "/ds"
      preLoaderRoute: typeof DsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_protected/account": {
      id: "/_protected/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/images/optimize": {
      id: "/api/images/optimize"
      path: "/api/images/optimize"
      fullPath: "/api/images/optimize"
      preLoaderRoute: typeof ApiImagesOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DsRoute: DsRoute,
  FaviconDotsvgRoute: FaviconDotsvgRoute,
  ProtectedAccountRoute: ProtectedAccountRoute,
  ApiImagesOptimizeRoute: ApiImagesOptimizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
